services:
  - type: web
    name: cas-interview-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
    ignoreFiles:
      - client/**
      - node_modules/**
      - package.json
      - package-lock.json 